spring:
  datasource:
    url: jdbc:h2:mem:usersDB
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8080
camel:
  springboot:
    name: UserService
sample:
  prop: "Ashish"
logging:
  level:
    com:
      zaxxer: INFO
